#%RAML 0.8
title: MSU People Search API
baseUri: http://hackathon-14.itservices.msu.edu/api/1
version: v1.0
/persons:
  get:
    queryParameters:
      msuNetId:
        description: Search by person MSU NetID
      lastName:
        description: Search by person last name
      firstName:
        description: Search by person first name
    description: Retrieving a record set of people that match the query parameters
  /{msunet}:
    get:
      body:
        application/json:
          schema:
            {
              "type": "object",
              "description": "string",
              "properties": {
                "title":  { "type": "string" },
                "firstName": { "type": "string" },
                "lastName": { "type": "string" },
                "employeeType": { "type": "string" },
                "mail": { "type": "string" },
                "tite": { "type": "string" },
                "department": { "type": "string" }
              }
            }
