#%RAML 0.8
title: MSU People Search API
baseUri: http://hackathon-14.itservices.msu.edu/api/1
version: v1.1
/persons:
  get:
    queryParameters:
      msunetid:
        description: Search by person MSU NetID
      lastname:
        description: Search by person last name
      firstname:
        description: Search by person first name
    description: Retrieving a record set of people that match the query parameters
  /{msunet}:
    get:
      body:
        application/json:
          schema:
            {
              "type": "object",
              "description": "string",
              "properties": {
                "firstName": { "type": "string" },
                "lastName": { "type": "string" },
                "title":  { "type": "string" },
                "employeeType": { "type": "string" },
                "email": { "type": "string" },
                "msuNetId": { "type": "string" },
                "department": { "type": "string" },
                "msunetid": { "type": "string" },
                "gravatar": { "type": "string" }
              }
            }
